/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsalesystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michael Paul Sebando
 */
public class ListOfUtangItems extends javax.swing.JFrame {

    /**
     * Creates new form ListOfUtangItems
     */
    public ListOfUtangItems() {
        initComponents();
        ImageIcon imgicon=new ImageIcon(getClass().getResource("/pointofsalesystem/Icons/POS Terminal_100px.png"));
        this.setIconImage(imgicon.getImage());
        this.setTitle("Purchased Items");
    }
    public void dispayUtang(int custId){
        int c_id=custId;
        String query="SELECT credit_sales.Quantity, menus.menuDesc, credit_sales.salesAmount FROM credit_sales INNER JOIN menus ON credit_sales.menuID=menus.menuID WHERE credit_sales.customerID='"+c_id+"'";
        try{
            Connection con=DBConnection.DBConnection();
            PreparedStatement pst=con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            DefaultTableModel dtm=(DefaultTableModel)OrderListTable.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("credit_sales.quantity"),rs.getString("menus.menuDesc"),rs.getString("credit_sales.salesAmount")};
                dtm.addRow(o);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderList = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderListTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderList.setBackground(new java.awt.Color(0, 255, 255));
        OrderList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderListTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderListTable.setForeground(new java.awt.Color(0, 204, 0));
        OrderListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTY", "ITEM", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderListTable.setGridColor(new java.awt.Color(255, 255, 255));
        OrderListTable.setRowHeight(22);
        OrderListTable.setSelectionBackground(new java.awt.Color(0, 204, 0));
        OrderListTable.setShowHorizontalLines(false);
        OrderListTable.setShowVerticalLines(false);
        OrderListTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                OrderListTableCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        OrderListTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OrderListTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(OrderListTable);
        if (OrderListTable.getColumnModel().getColumnCount() > 0) {
            OrderListTable.getColumnModel().getColumn(0).setPreferredWidth(16);
            OrderListTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 600, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Purchases");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 22));

        OrderList.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 600, 358));

        getContentPane().add(OrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OrderListTableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_OrderListTableCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderListTableCaretPositionChanged

    private void OrderListTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrderListTableKeyPressed
        
    }//GEN-LAST:event_OrderListTableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfUtangItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfUtangItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfUtangItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfUtangItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfUtangItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OrderList;
    private javax.swing.JTable OrderListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
