/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pointofsalesystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Paul Sebando
 */
public class RegistrationForm extends javax.swing.JFrame {

    /** Creates new form RegistrationForm */
    public RegistrationForm() {
        initComponents();
        ImageIcon imgicon=new ImageIcon(getClass().getResource("/pointofsalesystem/Icons/POS Terminal_100px.png"));
        this.setIconImage(imgicon.getImage());
        this.setTitle("Store Registration");
    }
    
    public void set_comp_name(String com_name){
        StoreName.setText(com_name);
    }
    private void validate_key(){
        try{
            Connection con=DBConnection.DBConnection();
            PreparedStatement pst=con.prepareStatement("SELECT * FROM reg_keys WHERE reg_key='"+RegKey.getText()+"'");
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                ValidationText.setForeground(Color.green);
                ValidationText.setText("Valid Product Key");
                Register.setEnabled(true);
            }
            else{
                
                Register.setEnabled(false);
                ValidationText.setForeground(Color.RED);
                ValidationText.setText("Invalid Product Key!");
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void register_store(){
        try{
            Connection con=DBConnection.DBConnection();
            PreparedStatement pst=con.prepareStatement("INSERT INTO systemstatus(reg_key, company_name, date_installed)"+"VALUES(?,?,?)");
            pst.setString(1, RegKey.getText());
            pst.setString(2, StoreName.getText());
            pst.setString(3, POSController.DateLabel.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Thank you for using my System!", "Success", JOptionPane.INFORMATION_MESSAGE);
            POSController pc=new POSController();
            pc.setVisible(true);
            dispose();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
                 
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Note = new javax.swing.JLabel();
        StoreName = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        Note1 = new javax.swing.JLabel();
        RegKey = new javax.swing.JTextField();
        ValidationText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("SYSTEM REGISTRATION");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 50));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Note.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Note.setForeground(new java.awt.Color(255, 204, 0));
        Note.setText("Store name");
        jPanel9.add(Note, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 30));

        StoreName.setEditable(false);
        StoreName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StoreName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(StoreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 370, 30));

        Register.setBackground(new java.awt.Color(0, 204, 0));
        Register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel9.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 170, 40));

        Note1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Note1.setForeground(new java.awt.Color(255, 204, 0));
        Note1.setText("Product Key");
        jPanel9.add(Note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        RegKey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegKey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RegKeyKeyReleased(evt);
            }
        });
        jPanel9.add(RegKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, 30));

        ValidationText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ValidationText.setForeground(new java.awt.Color(255, 51, 0));
        ValidationText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(ValidationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 340, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("Please contact the developer for Product Key");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 540, 200));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 560, 280));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Developed by CICT Team");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        if(RegKey.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your product key", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            register_store();
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void RegKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegKeyKeyReleased
        validate_key();
    }//GEN-LAST:event_RegKeyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Note;
    private javax.swing.JLabel Note1;
    private javax.swing.JTextField RegKey;
    private javax.swing.JButton Register;
    private javax.swing.JTextField StoreName;
    private javax.swing.JLabel ValidationText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

}
