/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsalesystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michael Paul Sebando
 */
public class UserManagement extends javax.swing.JFrame {
    Connection con=DBConnection.DBConnection();
    PreparedStatement pst;
    ResultSet rs;
    String userID;
    /**
     * Creates new form AddNewUser
     */
    public UserManagement() {
        initComponents();
        ImageIcon imgicon=new ImageIcon(getClass().getResource("/pointofsalesystem/Icons/POS Terminal_100px.png"));
        this.setIconImage(imgicon.getImage());
        this.setTitle("Users Management");
        showUsers();
    }
    private void AddUser(){
        try{
           if(AddButton.getText().equals("ADD")){
               pst=con.prepareStatement("SELECT * FROM accesslevel WHERE username='"+Username.getText()+"'");
               rs=pst.executeQuery();
               if(rs.next()){
                   Warnings.setText("Username is already taken!");
               }
               else{
                   pst=con.prepareStatement("INSERT INTO AccessLevel(username,password,fullname,role)"+"VALUES(?,?,?,?)");
                   pst.setString(1, Username.getText());
                   pst.setString(2, Password.getText());
                   pst.setString(3, FullName.getText().toUpperCase());
                   pst.setString(4, UserType.getSelectedItem().toString());
                   if(Username.getText().equals("")){
                       Warnings.setText("Username is Empty!");
                   }
                   else if(!Password.getText().equals(Password1.getText())){
                       Warnings.setText("Password does not match!");
                   }
                   else if(UserType.getSelectedItem().toString().equals("Select User Type")){
                       Warnings.setText("Please select user type!");
                   }
                   else{
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, FullName.getText()+" is successfully added!");
                        showUsers();
                   }
     
               }
               
           }
           else if(AddButton.getText().equals("UPDATE")){
                   pst=con.prepareStatement("UPDATE AccessLevel SET username=?,password=?,fullname=?,role=? WHERE userID='"+userID+"'");
                   pst.setString(1, Username.getText());
                   pst.setString(2, Password.getText());
                   pst.setString(3, FullName.getText().toUpperCase());
                   pst.setString(4, UserType.getSelectedItem().toString());
                   pst.executeUpdate();
                   JOptionPane.showMessageDialog(null, FullName.getText()+" is successfully updated!");
           }
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void showUsers(){
        try{
            pst=con.prepareStatement("SELECT * FROM AccessLevel ORDER BY fullname ASC");
            rs=pst.executeQuery();
            DefaultTableModel userList=(DefaultTableModel)TableUser.getModel();
            userList.setRowCount(0);
            while(rs.next()){
                Object users[]={rs.getString("fullname")};
                userList.addRow(users);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        FullName = new javax.swing.JTextField();
        Password1 = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        UserType = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        Warnings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("USER MANAGEMENT");
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Full Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Role");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Retype Password");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        Username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, -1));

        FullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        Password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, -1));

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, -1));

        UserType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Admin", "Cashier", "User" }));
        jPanel4.add(UserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 310));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TableUser.setBackground(new java.awt.Color(0, 0, 0));
        TableUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableUser.setForeground(new java.awt.Color(255, 204, 0));
        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User"
            }
        ));
        TableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableUser.setSelectionBackground(new java.awt.Color(0, 204, 0));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        TableUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableUserKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        AddButton.setBackground(new java.awt.Color(0, 204, 0));
        AddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsalesystem/Icons/Add User Male_48px.png"))); // NOI18N
        AddButton.setText("ADD");
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        Warnings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Warnings.setForeground(new java.awt.Color(255, 0, 0));
        Warnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Warnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Warnings, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 270, 310));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        String fullname=TableUser.getModel().getValueAt(TableUser.getSelectedRow(), 0).toString();
        try{
            pst=con.prepareStatement("SELECT * FROM AccessLevel WHERE fullname='"+fullname+"'");
            rs=pst.executeQuery();
            if(rs.next()){
                FullName.setText(rs.getString("fullname"));
                Username.setText(rs.getString("username"));
                Password.setText(rs.getString("password"));
                String role=rs.getString("role");
                if(role.equals("Admin")){
                    UserType.setSelectedIndex(1);
                }
                else{
                    UserType.setSelectedIndex(2);
                }
                AddButton.setText("UPDATE");
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_TableUserMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        AddUser();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void TableUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableUserKeyPressed
        char c = evt.getKeyChar();
      if (c == java.awt.event.KeyEvent.VK_DELETE){
          try{
              pst=con.prepareStatement("DELETE FROM AccessLevel WHERE fullname='"+TableUser.getModel().getValueAt(TableUser.getSelectedRow(), 0).toString()+"'");
              pst.executeUpdate();
              Warnings.setText("User deleted");
              showUsers();
          }
          catch(SQLException ex){
              JOptionPane.showMessageDialog(null, ex);
          }
      }
    }//GEN-LAST:event_TableUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField FullName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JTable TableUser;
    private javax.swing.JComboBox<String> UserType;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Warnings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
