/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeinformationsystem;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pswor
 */
public class AdminDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
        showUser();
       
    }
       private void showUser(){
           try{
           Connection conn=DatabaseConnection.DBConnect();
           String show="SELECT UserType, FullName, EmailAddress FROM ProgramUser WHERE Status='Active'";
           Statement stmnt=conn.createStatement();
           ResultSet resSet=stmnt.executeQuery(show);
           
           if(resSet.next()){
               String UserType=resSet.getString(1);
               String FullName=resSet.getString(2);
               String eAdd=resSet.getString(3);
               
               jusertype.setText(UserType);
               jfullname.setText(FullName);
               jemail.setText(eAdd);
               if(UserType.equals("User")){
                   AddUser.setEnabled(false);
                   AddNewDept.setEnabled(false);
                   ViewEmpDetail1.setEnabled(false);
               }
               else{
                  AddUser.setEnabled(true);
                   AddNewDept.setEnabled(true);
                   ViewEmpDetail1.setEnabled(true); 
               }
            }
           }
           catch(SQLException ex){
               JOptionPane.showMessageDialog(null, ex);
           }
       
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameBG = new javax.swing.JPanel();
        PanelDashBoard = new javax.swing.JPanel();
        AddUser = new javax.swing.JButton();
        AddNewDept = new javax.swing.JButton();
        ViewEmpDetail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jusertype = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jfullname = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ViewEmpDetail1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameBG.setBackground(new java.awt.Color(0, 0, 0));
        FrameBG.setPreferredSize(new java.awt.Dimension(729, 505));
        FrameBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDashBoard.setBackground(new java.awt.Color(0, 153, 153));
        PanelDashBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true), "ADMIN DASHBOARD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(51, 255, 255))); // NOI18N
        PanelDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddUser.setBackground(new java.awt.Color(0, 0, 0));
        AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeinformationsystem/Icons/Businessman_100px.png"))); // NOI18N
        AddUser.setBorder(null);
        AddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        PanelDashBoard.add(AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 44, 154, 142));

        AddNewDept.setBackground(new java.awt.Color(0, 0, 0));
        AddNewDept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeinformationsystem/Icons/Department_100px.png"))); // NOI18N
        AddNewDept.setBorder(null);
        AddNewDept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewDeptActionPerformed(evt);
            }
        });
        PanelDashBoard.add(AddNewDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 154, 142));

        ViewEmpDetail.setBackground(new java.awt.Color(0, 0, 0));
        ViewEmpDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeinformationsystem/Icons/Coworking_100px.png"))); // NOI18N
        ViewEmpDetail.setBorder(null);
        ViewEmpDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewEmpDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmpDetailActionPerformed(evt);
            }
        });
        PanelDashBoard.add(ViewEmpDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 44, 154, 142));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New User");
        PanelDashBoard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 204, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Employees");
        PanelDashBoard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 204, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add New Department");
        PanelDashBoard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true), "System Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("User:");

        jusertype.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jusertype.setText("Admin");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Name:");

        jfullname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jfullname.setText("Admin");

        jemail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jemail.setText("Admin");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("e-Mail:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jfullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(jusertype, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jusertype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jfullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jemail))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        PanelDashBoard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 44, -1, -1));

        ViewEmpDetail1.setBackground(new java.awt.Color(0, 0, 0));
        ViewEmpDetail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeinformationsystem/Icons/Coworking_100px.png"))); // NOI18N
        ViewEmpDetail1.setBorder(null);
        ViewEmpDetail1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewEmpDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmpDetail1ActionPerformed(evt);
            }
        });
        PanelDashBoard.add(ViewEmpDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 229, 154, 142));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Profile");
        PanelDashBoard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 389, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeeinformationsystem/Icons/Shutdown_30px.png"))); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelDashBoard.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 320, 260, 50));

        FrameBG.add(PanelDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 860, 430));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 5, true));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("EMPLOYEES INFORMATION SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        FrameBG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 550, 60));

        getContentPane().add(FrameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 880, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewEmpDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmpDetailActionPerformed
        EmployeeManagement em=new EmployeeManagement();
        em.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewEmpDetailActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Logout log=new Logout();
        log.Logout();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Logout log=new Logout();
        log.Logout();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        AddNewUser anu=new AddNewUser();
        anu.setVisible(true);
        
    }//GEN-LAST:event_AddUserActionPerformed

    private void AddNewDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewDeptActionPerformed
       AddNewDepartment and=new AddNewDepartment();
       and.setVisible(true);
       
    }//GEN-LAST:event_AddNewDeptActionPerformed

    private void ViewEmpDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmpDetail1ActionPerformed
        AddNewEmployee ane=new AddNewEmployee();
        ane.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewEmpDetail1ActionPerformed

 
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewDept;
    private javax.swing.JButton AddUser;
    private javax.swing.JPanel FrameBG;
    private javax.swing.JPanel PanelDashBoard;
    private javax.swing.JButton ViewEmpDetail;
    private javax.swing.JButton ViewEmpDetail1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jemail;
    private javax.swing.JLabel jfullname;
    private javax.swing.JLabel jusertype;
    // End of variables declaration//GEN-END:variables
}
